# ruff: noqa: E501
"""Curated hooks for Database.json rows 751–989 (239 words). Order matches data[750:].

Editorial tweaks vs raw user draft: Zenith (was confused with nadir); Polemic, Proclivity,
Sycophant, Turpitude, Turgid, Swarthy, Unctuous, Venerate (accuracy / tone / stereotypes).
"""
from __future__ import annotations

# Each entry: ("s"|"m"|"e", text) or None for null memoryHook.
ROWS: list[tuple[str, str] | None] = [
    ("s", "Plaza full - a plaza completely full of a massive overabundance of items."),
    ("s", "Ply - like plywood, it bends easily and is highly flexible."),
    ("s", "Point - a sad memory so sharp it feels like it points straight into your heart."),
    ("s", "Polemic = debate weaponized: a blistering attack essay or speech against a person or idea."),
    ("s", "Important - a highly important sign that something terrible is about to happen."),
    ("s", "Pot - water safe enough to boil in a pot and drink."),
    ("m", '"potent" (powerful) = an incredibly powerful ruler or dictator.'),
    None,
    ("s", "Press of ice - standing dangerously on the very edge of a massive cliff of ice."),
    ("m", '"pre-" (before) + "cludere" (shut) = shut the door before it happens, making it impossible.'),
    ("e", 'Latin praecox ("cooked before"): a child whose mind has "cooked" ahead of schedule.'),
    ("s", "Pre-direction - you lean in a pre-direction because you have a strong preference for it."),
    ("m", '"pre-" (before) + "ponder" (weigh) = an amount so massive it outweighs everything else.'),
    ("s", "Possess - someone so attractive you want to possess their attention."),
    ("m", '"pre-" (before) + "sage" (wise) = wise intuition that reads what is coming before it arrives.'),
    ("m", '"pre-" (before) + "sci" (know) = knowing what will happen before it does.'),
    None,
    None,
    None,
    ("m", '"prim" (first) + "ev" (age) = relating to the very first, ancient ages of the earth.'),
    ("s", "Deprive - a state of extreme poverty where you are deprived of basic needs."),
    ("s", "Probe - a politician whose morals are so flawless they withstand the deepest legal probe."),
    ("s", "Incline-built - in lean toward a habit; a tendency so steady it feels like gravity."),
    None,
    ("m", '"pro-" (outside) + "fanum" (temple) = disrespect spoken outside the sacred space.'),
    ("s", "Profits gate - throwing profits out the gate because you are reckless with money."),
    ("m", '"pro-" (forth) + "fundere" (pour) = pouring forth in massive abundant quantities.'),
    ("s", "Prom gate - announcing new rules loudly right at the prom gate."),
    None,
    ("s", "Pro pen - a writer with a natural tendency to always grab a pro pen."),
    ("s", "Profits - conditions look favorable; strong signs you could see big profits."),
    ("s", "Proper - acting with strict, perfectly proper, socially acceptable behavior."),
    ("s", "Prose - writing that sounds like ordinary prose instead of poetry; dull."),
    ("m", '"pro-" (before) + "scribere" (write) = write a name on a list to legally forbid someone.'),
    ("e", "From Proteus, Greek sea god who changed shape to escape - versatile, constantly shifting."),
    None,
    ("s", "Prude - so careful and cautious with choices that people joke you are a prude."),
    None,
    ("s", "Pure ill - a child acting so immaturely it makes you feel purely ill."),
    ("m", '"pugn" (fight) = eager to argue or fight; combative energy.'),
    ("s", "Pull attitude - beauty so strong it pulls the room's attitude toward you."),
    ("s", "Punctuation - obsessed with tiny details; corrects your text-message punctuation."),
    ("s", "Punch in - a smell so sharp it punches you in the nose."),
    ("m", '"pun" (punish) = intended to punish, not merely to correct.'),
    ("s", "Puke - rot so foul it makes you want to puke."),
    ("s", "Quack mire - a duck stuck in a muddy, complicated swamp."),
    None,
    ("s", "Wandering - wandering lost because you are stuck in painful uncertainty."),
    ("s", "Quiet well - force quiets the riot well."),
    ("s", "Quarrel - whining and always ready to pick a petty quarrel."),
    ("e", "Don Quixote charged windmills as giants - idealistic but impractical."),
    ("s", "Quota - same boring daily quota; ordinary everyday life."),
    ("s", "Derail - ranting so hard you try to derail the meeting."),
    None,
    ("s", "Rank core - bitter hatred sitting in the core of your heart."),
    None,
    None,
    ("s", "Ruckus - a loud chaotic crowd making a ruckus."),
    ("s", "Razor - bulldozing a building down as if shaved by a razor."),
    None,
    ("m", '"re-" (back) + "calcitrare" (kick) = kicking back; stubbornly disobedient.'),
    ("m", '"re-" (again) + "capit" (head) = revisit the main heads or points in summary.'),
    None,
    ("m", '"re-" (back) + "clus" (shut) = shut away from the world; withdrawn.'),
    None,
    ("m", '"rect" (straight/right) = upright, morally straight behavior.'),
    ("s", "Doubt - an opponent so intimidating you doubt you can win."),
    None,
    None,
    None,
    None,
    ("s", "Relocate - moved down to a lower, less important rank or role."),
    ("s", "Hot dog relish - savoring a moment the way you savor relish on a hot dog."),
    None,
    ("s", "Miss - careless with duty so you miss the deadline entirely."),
    None,
    None,
    ("m", '"re-" (back) + "nuntiare" (announce) = announce you formally renounce a claim.'),
    None,
    ("m", '"re-" (again) + "plere" (fill) = filled back up to maximum capacity.'),
    ("s", "Pose - lying still in a calm resting pose."),
    ("s", "Apprehend - behavior so bad the police should apprehend you."),
    None,
    ("s", "Roach - scolding the owner for a roach in the kitchen."),
    ("s", "Probation - a scoundrel who failed probation and slid back to trouble."),
    ("s", "Prove - scolding someone until they prove they will not repeat it."),
    ("s", "Refuse it - reject a claim and refuse it as false."),
    ("m", '"re-" (back) + "puls" (drive) = drive an attack or feeling back.'),
    None,
    None,
    ("s", "Send back - cancel an order and send it entirely back."),
    None,
    ("m", '"re-" (back) + "salire" (jump) = bounce back after a hard hit.'),
    ("s", "Resolution - a firm resolution you refuse to break."),
    None,
    ("s", "Rest bit - a badly needed rest bit during an exhausting hike."),
    ("s", "Splendid - shining so bright it looks splendid."),
    ("s", "Restore - paying or working to restore what was stolen or broken."),
    ("s", "Restless - a horse tense and restless, unable to stand still."),
    ("m", '"re-" (back) + "tract" (pull) = formally pull back a false statement.'),
    ("s", "Rebel - the rebel parties all night after a wild win."),
    ("s", "Reverend - deep respectful awe, like toward a reverend."),
    ("m", '"re-" (back) + "voc" (call) = call a license back and cancel it.'),
    ("s", "Rap song - praising or ranting with the heat of a passionate rap."),
    ("s", "Rip bawd - coarse, lewd humor ripped from the tavern; indecent and deliberately shocking."),
    ("s", "Rifle - an area rife with rifles; common and dangerous."),
    ("e", "Latin ruminare (chew the cud) - chew the same thought over and over."),
    ("s", "Confuse - a trick meant to confuse the enemy."),
    ("s", "Saccharin - sweetness as fake as the sweetener; cloying and artificial."),
    ("m", '"sacro" (sacred) + "sanct" (holy) = doubly sacred; not to be violated.'),
    ("s", "Sage - the deep judgment of a wise sage."),
    ("s", "Sail - the main sail is the most salient feature on the boat."),
    None,
    ("s", "Solve - ointment that soothes a burn and solves the worst of the sting."),
    ("m", '"sanct" (holy) = acting holier-than-thou to claim moral high ground.'),
    ("e", 'Latin sanguis (blood): old humor theory tied blood tone to confident optimism.'),
    ("s", "Satisfy ate - you ate enough to satisfy brutal hunger."),
    ("s", "Scalding - a review that scalds; harshly critical."),
    ("s", "Sparkling - wit and energy sparkling like champagne bubbles."),
    ("s", "Scrap - checking every scrap because honesty demands perfect detail."),
    ("s", "Scurry - ugly rumors that make the target want to scurry away."),
    ("m", '"sed" (sit) = life spent sitting; little movement.'),
    None,
    ("m", '"semin" (seed) = a seed idea that spawns a whole field of later work.'),
    None,
    None,
    ("e", 'Walpole coined it from "The Three Princes of Serendip"-lucky finds by accident.'),
    None,
    ("m", '"serv" (serve/slave) = groveling, excessively submissive.'),
    ("s", "Sinus - a road winding like sinus passages; serpentine curves."),
    None,
    ("s", "Sole - hovering over whether your shoe sole is hurting your foot."),
    ("m", '"solus" (alone) + "ipse" (self) = the world is only "me" in your mind.'),
    None,
    ("s", "Solve rent - cash flow strong enough to solve rent and pay debts."),
    ("m", '"somn" (sleep) = drowsy, ready to nod off.'),
    ("s", "Sophomore - acting like a cocky, immature sophomore."),
    None,
    None,
    ("s", "Furious - the judge furious at evidence that is clearly fake."),
    None,
    ("s", "Stayed - so staid they stayed home; serious, steady, unflashy."),
    None,
    ("e", "From the Stoa Poikile porch where Zeno taught - endure pain without theatrics."),
    ("s", "Solid - emotionally solid like a brick wall; unmovable."),
    None,
    ("s", "Trident - noise as harsh as a trident slammed into stone."),
    ("s", "Stupid - shocked stupid; brain freezes for a moment."),
    ("m", '"sub" (under) + "jugum" (yoke) = bring a people under your yoke.'),
    None,
    None,
    ("s", "Sucked in - speech with extra words sucked in; tight and brief."),
    ("m", '"super" (over) + "flu" (flow) = extra detail flowing over the brim.'),
    ("s", "Surf it - so many waves you cannot surf them all; excess."),
    ("s", "Summarize - guess the whole plot from scraps, like forced summarizing."),
    ("s", "Syrup - pouring extra syrup when nobody is watching."),
    None,
    ("s", 'Weather-line-outdoor life etched into complexion (literary "swarth" tones).'),
    ("s", "Psyche + fawn - flatters power to win favor; a professional bootlicker."),
    ("s", "Take it - a silent deal where everyone takes it and says nothing."),
    ("m", '"tacit" (silent) = habitually quiet; not chatty.'),
    ("s", "Tangent - barely grazing the topic; flies off on a tangent."),
    ("s", "Total amount - equivalent in seriousness or value to another total."),
    None,
    ("s", "Team error - reckless nerve to blame the whole team error on the boss."),
    None,
    ("m", '"tenere" (hold) = an argument you can hold up under scrutiny.'),
    ("s", "Ten percent grip - holding the rope by the thinnest tenth; shaky."),
    None,
    ("s", "Tremble - timid and trembling like a frightened mouse."),
    ("s", "Tired - a long angry speech that leaves everyone tired."),
    ("s", "Toad - creeping praise like a toad at the tyrant's foot."),
    ("s", "Tomb - a huge tome as heavy as a tombstone."),
    ("s", "Torpedo - floating sluggish like a torpedo before launch."),
    ("s", "Tear it - passion so hot it tears at restraint; scorching heat."),
    ("s", "Torture - path so twisting it feels like torture to navigate."),
    ("m", '"tract" (lead/manage) = easy to lead; docile and manageable.'),
    None,
    ("m", '"trans" (across) + "gress" (step) = step across a moral line you should not.'),
    ("m", '"trans" (across) + "ire" (go) = passing through; not staying long.'),
    ("m", '"trans" (across) + "mut" (change) = change something into another substance.'),
    ("s", "Tragedy - a mockery of justice so bad it is a tragedy."),
    ("s", "Tremble - voice trembling from fear."),
    ("s", "Trench - criticism that cuts a deep trench."),
    ("s", "Trap - dread that you are walking into a trap."),
    ("s", "Tripe - an idea as tired as cheap tripe."),
    ("s", "Truck - aggressive like a truck ready to run you down."),
    ("s", "Trunk - chop at the trunk to shorten the tree."),
    ("s", "Turgid = swollen - bloated language or tissue, overstuffed and heavy (not muddy/turbid)."),
    ("s", "Moral filth - conduct courts label crimes of moral turpitude; deep baseness."),
    ("m", '"ubique" (everywhere) = showing up everywhere at once.'),
    ("m", '"umbr" (shadow) = take offense as if a disrespectful shadow fell on you.'),
    None,
    ("s", "Oil-on-tone - flattery so smooth it feels greasy; slick, insincere charm."),
    ("s", "Undulate - waves moving under the surface in smooth rolls."),
    ("s", "Braid - scolding someone for ruining your careful braid."),
    ("s", "Use up - seize power to use up what is left of the kingdom."),
    None,
    ("e", 'More coined "Utopia" from ou + topos ("no place")-a perfect society that cannot exist.'),
    ("s", "Vase - wavering forever between two vases you cannot choose."),
    ("m", '"vac" (empty) = empty behind the eyes; mindless.'),
    None,
    ("s", "Vapor - remark so dull it evaporates like vapor."),
    ("m", '"varius" (various) = patched with varied colors or tones.'),
    ("s", "Vehicle - yelling with full heat at the car that cut you off."),
    None,
    ("m", '"venerari" (respect) = worthy of reverence for age, dignity, or achievement.'),
    ("s", "Revere-plus - honor deeply as if before something sacred (same family as reverent)."),
    ("m", '"ver" (truth) = truthfulness you can stake a claim on.'),
    ("m", '"verb" (word) = padded with too many words; talky and windy.'),
    ("m", '"virid" (green) = green with lush growth.'),
    ("s", "Vest - only a ripped old vest remains as a trace of the wreck."),
    ("s", "Hex - annoy someone as if you cast a petty hex on them."),
    ("s", "Borrowed thrill - living someone else's excitement secondhand."),
    None,
    None,
    ("m", '"vilis" (vile) + " - fy" (make) = talk someone into looking vile.'),
    ("m", "Vindicare - show the accusation was false; clear a ruined name."),
    ("s", "Victim - wanting the other side to become your suffering victim."),
    None,
    ("s", "Viscosity - thick, sticky, slow to pour."),
    ("s", "Vitriol - words as burning as strong acid."),
    ("s", "Viper - hissing insults with viper venom."),
    ("m", '"viv" (life) = lively, bubbling with life.'),
    ("m", '"voc" (call) = a career that feels like a calling.'),
    ("m", '"voc" (voice) + "ferre" (carry) = carrying a loud voice into the room.'),
    None,
    ("s", "Wayne - Wayne Enterprises lights dimming as Bruce fades after a brutal night."),
    ("s", "Wonton - wanton waste of a whole bowl of wonton soup on purpose; reckless malice."),
    None,
    ("s", "Wile E. - cunning traps and scams like the cartoon coyote."),
    ("s", "Win some - charm that wins some hearts instantly."),
    ("s", "Wishful - nostalgia colored by sad wishful longing."),
    ("s", "Wizard - face wizened like a storybook wizard: shriveled and lined."),
    None,
    None,
    ("s", "Jealous - fire of a jealous lover turned toward a cause; fiercely devoted."),
    ("s", "Zenith tip - apex of the arc (sun at noon); your highest point, not the bottom below."),
    ("s", "Zero fear - breeze so gentle it gives you zero fear of a storm."),
]
