#!/usr/bin/env python3
"""Emit scripts/batch_003_hooks.tsv from HOOK_ROWS (user batch 003). Run from repo root or scripts/."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "batch_003_hooks.tsv"

# (word, "s"|"m"|"e"|"n", text) - text ignored when kind is "n"
HOOK_ROWS: list[tuple[str, str, str]] = [
    ("Grandiloquence", "m", '"grand" (great) + "loqu" (speak) = speaking in a massive, overly pompous way.'),
    ("Grandiose", "n", ""),
    ("Gratuitous", "s", "Gratuity-adding an unnecessary, uncalled-for extra tip when the service was already bad."),
    ("Gregarious", "m", '"greg" (flock) = loving to be part of the flock; highly sociable and outgoing.'),
    ("Grievous", "s", "Grief-an injury or mistake so severe that it causes immense grief."),
    ("Guile", "s", "Disguise-a criminal using a clever disguise out of pure guile and trickery."),
    ("Hackneyed", "e", "From Hackney, an area in London where horses were bred to be rented out. The horses became so overworked and common that the word evolved to mean any phrase or idea that is heavily overused and totally unoriginal."),
    ("Hallowed", "s", "Halloween (All Hallows' Eve)-referring to the most holy, deeply respected evening."),
    ("Hapless", "m", '"hap" (luck/chance) + "less" = entirely without luck; doomed.'),
    ("Harangue", "s", "Hear anger-a long, aggressive speech where all you hear is the speaker's intense anger."),
    ("Hardy", "s", "Hard-a plant or person tough enough to survive extremely hard, freezing conditions."),
    ("Harrowing", "s", "Arrowing-being shot at by a rain of flying arrows is a terrifying, highly distressing experience."),
    ("Haughty", "s", "High-acting incredibly high and mighty, looking down on everyone else."),
    ("Hedonist", "s", 'He done it-"He done it" just for the sheer thrill, because a hedonist lives strictly for physical pleasure.'),
    ("Hegemony", "s", "Huge money-the empire with huge money has absolute dominance and control over the weaker nations."),
    ("Heinous", "s", "Hate us-committing crimes so terribly wicked they make the entire world hate us."),
    ("Heterogeneous", "m", '"hetero" (different) + "gen" (kind) = made up of completely different, varied parts.'),
    ("Hiatus", "s", 'Hide us-the famous band begging "hide us" so they can take a long, badly needed break from the public.'),
    ("Hierarchy", "n", ""),
    ("Hypocrisy", "n", ""),
    ("Hypothetical", "n", ""),
    ("Iconoclast", "m", '"icon" (image) + "clast" (breaker) = a rebel who attacks and breaks heavily established traditions and beliefs.'),
    ("Idiosyncratic", "m", '"idio" (peculiar/self) = a highly unique, strange trait specific to one individual.'),
    ("Idolatrous", "m", '"idol" = worshiping an idol or a person to an excessive, blind degree.'),
    ("Ignominious", "m", '"ig-" (not) + "nomin" (name) = having your good name totally destroyed; suffering a disgraceful public defeat.'),
    ("Illicit", "s", "Ill-doing highly illegal things that make society ill."),
    ("Immerse", "n", ""),
    ("Immutable", "m", '"im-" (not) + "mut" (change) = a law of physics that is entirely unable to be mutated or changed.'),
    ("Impassive", "m", '"im-" (not) + "pass" (feeling) = an expression showing absolutely zero emotion or feeling.'),
    ("Impeccable", "m", '"im-" (not) + "pecc" (sin) = a performance or outfit that is entirely without sin or flaw.'),
    ("Impecunious", "m", '"im-" (not) + "pecun" (money) = having absolutely no money.'),
    ("Imperative", "n", ""),
    ("Imperious", "s", "Emperor-acting like a bossy, highly arrogant emperor barking orders."),
    ("Impertinent", "m", '"im-" (not) + "pertinent" (proper/relevant) = acting outside the bounds of proper respect; incredibly rude to an authority figure.'),
    ("Impervious", "m", '"im-" (not) + "per" (through) + "via" (way) = providing no way through; a raincoat impervious to water.'),
    ("Impetuous", "s", "Impulse-acting strictly on wild impulse without thinking of the consequences."),
    ("Impinge", "s", "Pinch-encroaching on someone's personal space until you literally pinch them."),
    ("Implacable", "m", '"im-" (not) + "plac" (calm/please) = an enemy whose raging anger is impossible to calm down.'),
    ("Implement", "n", ""),
    ("Implicate", "n", ""),
    ("Implicit", "n", ""),
    ("Impregnable", "m", '"im-" (not) + "pregnable" (vulnerable to capture) = a heavy stone fortress that is impossible to break into.'),
    ("Impudent", "s", "Rude student-a highly bold, shamelessly disrespectful student backtalking the principal."),
    ("Impute", "s", "Put-to put the blame for the mistake directly onto someone else's record."),
    ("Inane", "s", "Insane-a comment so painfully empty and silly it borders on insane."),
    ("Inarticulate", "m", '"in-" (not) + "articulate" = entirely unable to speak clearly or express thoughts.'),
    ("Incarnate", "m", '"in-" (in) + "carn" (flesh) = a spirit or idea given physical, bodily form in the flesh.'),
    ("Incendiary", "m", '"incend" (fire) = a bomb or a speech specifically designed to cause massive fires or conflict.'),
    ("Incessant", "m", '"in-" (not) + "cess" (stop) = a dripping faucet that is never stopping.'),
    ("Inchoate", "s", "Inches-a business plan that is only a few inches along; just barely starting and completely unformed."),
    ("Incisive", "m", '"in-" (into) + "caedere" (cut) = mental analysis that cuts straight to the heart of the matter; razor-sharp.'),
    ("Inclination", "n", ""),
    ("Incontrovertible", "m", '"in-" (not) + "controvert" (dispute) = DNA evidence that is entirely impossible to argue against.'),
    ("Incorrigible", "m", '"in-" (not) + "corrigere" (correct) = a criminal so deeply bad they are completely beyond correction.'),
    ("Increment", "n", ""),
    # Safer than suggestive pun: still sound-adjacent to *incumbent*
    ("Incumbent", "s", "Occupies the seat now-the officeholder already in power (the one whose role is filled)."),
    ("Indefatigable", "m", '"in-" (not) + "defatigate" (tire) = a marathon runner whose energy is impossible to tire out.'),
    ("Indigenous", "n", ""),
    ("Indigent", "s", "Dig in dirt-someone so desperately poor they have to dig in the dirt to find food."),
    ("Indignation", "m", '"in-" (not) + "dign" (worthy) = fierce anger sparked by being treated in a completely unworthy or unfair way.'),
    ("Indolent", "s", "Indoor tent-laying lazily in an indoor tent all day doing absolutely nothing."),
    ("Indomitable", "m", '"in-" (not) + "domit" (tame) = an underdog spirit that is impossible to crush or tame.'),
    ("Induce", "n", ""),
    ("Ineffable", "m", '"in-" (not) + "effable" (speakable) = looking at the Grand Canyon and feeling an awe so immense it cannot be expressed in words.'),
    ("Inept", "m", '"in-" (not) + "apt" (skilled) = entirely clumsy and lacking any skill for the job.'),
    ("Inexorable", "m", '"in-" (not) + "exorare" (persuade) = the marching army was impossible to persuade or stop.'),
    ("Inextricable", "m", '"in-" (not) + "extricate" (untangle) = two headphones hopelessly and impossibly tangled together.'),
    ("Infamy", "m", '"in-" (not) + "fame" = possessing world fame, but strictly for highly evil reasons.'),
    ("Infusion", "n", ""),
    ("Ingenious", "n", ""),
    ("Ingenuous", "s", "Genuine-someone with a highly innocent, trusting, and completely genuine nature."),
    ("Inhibit", "n", ""),
    ("Inimical", "m", '"in-" (not) + "amicus" (friend) = deeply unfriendly, hostile, and actively harmful.'),
    ("Iniquity", "m", '"in-" (not) + "equ" (fair/equal) = a situation of gross injustice or deeply wicked behavior.'),
    ("Injunction", "n", ""),
    ("Innate", "m", '"in-" (in) + "nat" (born) = a perfect pitch musical talent you were naturally born with.'),
    ("Innocuous", "m", '"in-" (not) + "noc" (harm) = entirely safe and harmless.'),
    ("Innovate", "n", ""),
    ("Innuendo", "n", ""),
    ("Inoculate", "n", ""),
    ("Inquisitor", "n", ""),
    ("Insatiable", "m", '"in-" (not) + "satiable" (satisfied) = a hunger for power that is absolutely impossible to satisfy.'),
    ("Insidious", "s", "Inside us-a dangerous, sneaky disease spreading quietly inside us without being noticed until it's too late."),
    ("Insinuate", "n", ""),
    ("Insipid", "s", "Sip it-the tea is so totally flavorless and boring you can barely force yourself to sip it."),
    ("Insolent", "s", "Insulting-a teenager showing an incredibly rude and insulting lack of respect to a judge."),
    ("Instigate", "n", ""),
    ("Insular", "m", '"insula" (island) = having a highly isolated and narrow-minded worldview, living purely on a cultural island.'),
    ("Insurgent", "m", '"in-" (against) + "surgere" (rise) = rebels rising up violently against the established government.'),
    ("Integral", "n", ""),
    ("Interject", "m", '"inter" (between) + "ject" (throw) = sharply throwing your own comment between other speakers\' words.'),
    ("Interlocutor", "m", '"inter" (between) + "loc" (speak) = the specific person you are speaking back and forth with in a conversation.'),
    ("Interminable", "m", '"in-" (not) + "termin" (end) = a boring university lecture that feels completely endless.'),
    ("Intimation", "s", "Intimate-quietly sharing a very subtle, intimate hint rather than a direct statement."),
    ("Intractable", "m", '"in-" (not) + "tract" (pull/manage) = a highly stubborn problem or person that is utterly unmanageable.'),
    ("Intransigent", "s", "Transfer-a negotiator aggressively refusing to transfer or compromise their original position."),
    ("Intrepid", "m", '"in-" (not) + "trepidus" (alarmed) = an explorer who is completely fearless and undaunted by danger.'),
    ("Inundate", "m", '"in-" (into) + "unda" (wave) = being completely flooded by a massive wave of emails or tasks.'),
    ("Inure", "s", "In your-the freezing cold has been in your life for so long you've grown completely numb and used to it."),
    ("Invective", "s", "Infective-highly abusive, toxic language that spreads through a crowd like an infection."),
    ("Inveterate", "m", '"in-" (in) + "veter" (old) = an extremely old, deeply established habit you cannot break.'),
    ("Inviolable", "m", '"in-" (not) + "violable" = an absolute rule that is entirely safe from being violated or broken.'),
    ("Irascible", "s", "Erasable-a teacher with a terrible temper who violently snaps when you use an un-erasable pen on the whiteboard."),
    ("Iridescent", "n", ""),
    ("Irreverence", "m", '"ir-" (not) + "revere" (respect) = laughing out loud at a funeral; showing a complete lack of proper respect.'),
    ("Irrevocable", "m", '"ir-" (not) + "re" (back) + "voc" (call) = a final decision that can absolutely never be called back.'),
    ("Jubilant", "s", "Jubilee-a massive, roaring celebration full of intense joy."),
    ("Judicious", "m", '"jud" (judge) = a leader possessing incredibly good, careful judgment.'),
    ("Juxtaposition", "n", ""),
    ("Knell", "s", "Bell-the incredibly slow, solemn ringing of a funeral bell."),
    ("Kudos", "n", ""),
    ("Laceration", "n", ""),
    ("Laconic", "e", "From Laconia, the region of ancient Sparta. The Spartans were highly famous for giving incredibly brief, blunt, and tough answers to their enemies."),
    ("Languid", "s", "Language-speaking in a highly slow, tired, and lazy language because you have zero energy."),
    ("Larceny", "n", ""),
    ("Largess", "s", "Large-a highly generous billionaire handing out large sums of cash to charity."),
    ("Latent", "s", "Late tent-the true talent is hiding asleep in the tent, waiting to emerge late in the game."),
    ("Laudatory", "m", '"laud" (praise) = a speech expressing intense, glowing praise for a hero.'),
    ("Lavish", "n", ""),
    ("Legerdemain", "e", 'From the French phrase léger de main meaning "light of hand." It is exactly the skill a magician or pickpocket uses for sleight of hand trickery.'),
    ("Lenient", "n", ""),
    ("Lethargic", "n", ""),
    ("Liability", "n", ""),
    ("Libertarian", "n", ""),
    ("Licentious", "s", "License-acting recklessly, as if you have a government license to break all moral and sexual rules."),
    ("Limpid", "s", "Liquid-a mountain stream that is completely clear, pure, and see-through liquid."),
    ("Linchpin", "n", ""),
    ("Lithe", "n", ""),
    ("Litigant", "n", ""),
    ("Lucid", "m", '"luc" (light) = a complex argument suddenly made completely clear and brilliantly illuminated.'),
    ("Luminous", "m", '"lumin" (light) = brightly shining and radiating light.'),
    ("Lurid", "s", "Lure in-a tabloid using violently graphic, shocking headlines strictly to lure readers in."),
    ("Maelstrom", "n", ""),
    ("Magnanimous", "m", '"magn" (great) + "anim" (spirit) = a leader with a massive, highly forgiving spirit toward defeated enemies.'),
    ("Malediction", "m", '"mal" (bad) + "dict" (speak) = a witch speaking a dark, terrible curse over a village.'),
    ("Malevolent", "m", '"mal" (bad) + "vol" (wish) = heavily wishing severe evil and harm on others.'),
    ("Malleable", "s", "Mallet-a metal that is soft and flexible enough to be easily shaped by a mallet."),
    ("Mandate", "n", ""),
    ("Manifest", "n", ""),
    ("Manifold", "m", '"mani" (many) + "fold" = having many different, highly diverse folds or forms.'),
    ("Maudlin", "s", "Model in-a model in a cheap soap opera crying excessively and artificially over a tiny broken nail."),
    ("Maverick", "e", "Named after Samuel Maverick, an 1800s Texas rancher who famously refused to brand his cattle. It completely evolved to mean any independent rebel who refuses to follow the herd."),
    ("Mawkish", "s", "Ma kiss-your Ma aggressively kissing your cheek in front of your high school friends; overly sentimental and sickening."),
    ("Maxim", "s", "Maximum-a highly condensed, short phrase carrying the absolute maximum amount of truth."),
    ("Meager", "n", ""),
    ("Medley", "n", ""),
    ("Mendacious", "s", "Mend-having to desperately mend your story because you were caught being highly deceitful and lying."),
    ("Mercurial", "e", "Derived from the Roman god Mercury (and the liquid metal). Describes someone prone to incredibly rapid, unpredictable, and explosive mood changes."),
    ("Meritorious", "m", '"merit" (deserve) = an action highly deserving of intense praise and reward.'),
    ("Metamorphosis", "m", '"meta" (change) + "morph" (shape) = a caterpillar undergoing a complete physical transformation into a butterfly.'),
    ("Meticulous", "n", ""),
    ("Mitigate", "n", ""),
    ("Moderate", "n", ""),
    ("Modicum", "s", "Modest crumb-having only a tiny, extremely modest crumb of respect left for someone."),
    ("Modulate", "n", ""),
    ("Mollify", "m", '"moll" (soft) + "fy" (make) = to completely soften someone\'s raging anger with an apology.'),
    # Classroom-safe swap for crude pun
    ("Morass", "s", "More mass-every step sinks deeper; a hopeless mix of mud, mess, and delay."),
    ("Mores", "s", "Morals-the absolutely fundamental moral customs and unwritten rules of a group."),
    ("Morose", "s", "No rose-being incredibly depressed, sullen, and gloomy because you got no rose on Valentine's Day."),
    ("Multifarious", "m", '"multi" (many) = a museum collection having many extremely diverse, varied parts.'),
    ("Mundane", "m", '"mund" (world) = an ordinary, highly boring task related purely to the earthly world rather than the exciting heavens.'),
    ("Munificence", "m", '"muni" (gift) + "fic" (make) = making incredibly generous, massive financial gifts.'),
    ("Mutable", "m", '"mut" (change) = a situation that is highly prone to constant change.'),
    ("Myriad", "s", "Pyramid-a myriad of heavy stone blocks were used to build the massive pyramid (meaning countless or extremely high in number)."),
    ("Nadir", "s", "Nada-hitting absolute rock bottom where you have completely nada (nothing) left."),
    ("Nascent", "s", "New scent-a brand new born project having a nascent, totally fresh scent."),
    ("Nebulous", "m", '"nebul" (cloud) = an idea that is highly cloudy, vague, and undefined.'),
    ("Nefarious", "s", "No fairness-an utterly evil villain acting with absolutely zero fairness."),
    ("Negligent", "n", ""),
    ("Neophyte", "m", '"neo" (new) + "phyt" (plant) = a newly planted convert; an absolute, raw beginner.'),
    ("Nocturnal", "m", '"noct" (night) = a predator highly active only in the dead of night.'),
    ("Noisome", "s", "Nose-an odor so absolutely foul and toxic it physically attacks your nose."),
    ("Nomadic", "n", ""),
    ("Nominal", "m", '"nomin" (name) = the king holds power in name only; the actual amount of control is incredibly tiny.'),
    ("Nonchalant", "n", ""),
    ("Nondescript", "n", ""),
    ("Notorious", "n", ""),
    ("Novice", "n", ""),
    ("Noxious", "m", '"nox" (harm) = highly toxic, poisonous, and physically harmful gas.'),
    ("Nuance", "n", ""),
    ("Nurture", "n", ""),
    ("Obdurate", "m", '"ob" (against) + "dur" (hard) = having a completely hardened heart against any persuasion or pity.'),
    ("Obfuscate", "m", '"ob" (against) + "fuscare" (darken) = to completely darken or hide the truth to confuse the public.'),
    ("Oblique", "s", "Ob-look-taking an indirect, highly slanted look at the problem rather than attacking it straight on."),
    ("Oblivious", "n", ""),
    ("Obscure", "n", ""),
    ("Obsequious", "s", "Obsessed yes-fawning on authority, agreeing endlessly to stay in the boss's good graces."),
    ("Obsolete", "n", ""),
    ("Obstinate", "n", ""),
    ("Obstreperous", "s", "Street prep-a loud, completely unruly crowd causing wild chaos while prepping in the street."),
    ("Obtuse", "n", ""),
    ("Odious", "s", "Odor-a personality or crime so deeply repulsive it hits you like a foul, sickening odor."),
    ("Officious", "s", "Office boss-an annoying, low-level coworker acting exactly like the office boss and aggressively meddling in your work."),
    ("Ominous", "s", "Omen-dark storm clouds giving a threatening omen that something very bad is coming."),
    ("Onerous", "s", "On us-an incredibly heavy, punishingly difficult burden placed squarely on us."),
    ("Opulent", "s", "Opal-a massive mansion dripping in opals, diamonds, and sheer, excessive wealth."),
    ("Oration", "n", ""),
    ("Ornate", "n", ""),
    ("Orthodox", "m", '"ortho" (straight/correct) + "dox" (belief) = following the strictly established, completely traditional beliefs.'),
    ("Oscillate", "n", ""),
    ("Ostensible", "s", "Sensible-presenting a sensible-sounding, fake excuse that completely hides your true motive."),
    ("Ostentatious", "s", "Ostrich-walking around in an enormous ostrich-feather hat specifically to aggressively show off your wealth."),
    ("Ostracism", "e", 'From ancient Athens, where citizens voted to banish dangerous politicians from the city by writing their names on pieces of broken pottery called "ostraka."'),
    ("Pacific", "m", '"pac" (peace) = a demeanor that is deeply calm, tranquil, and peaceful (like the Pacific Ocean).'),
    ("Palatable", "s", "Plate-the strange food on the plate is finally agreeable and okay to your taste."),
    ("Palette", "n", ""),
    ("Palliate", "s", "Pill ate-you ate a pill to soothe and hide the severe symptoms, even though it didn't actually cure the disease."),
    ("Pallid", "s", "Pale-a completely pale, sickly, and utterly lifeless face."),
    ("Panacea", "m", '"pan" (all) + "akos" (cure) = a mythical, highly sought-after cure-all for absolutely every disease.'),
    ("Paradigm", "n", ""),
    ("Paradox", "n", ""),
    ("Paragon", "n", ""),
    ("Paramount", "s", "Mountain-sitting at the absolute highest, most supreme mountain peak of importance."),
    ("Pariah", "s", "Mariah-Mariah acted so wildly that the entire town exiled her as a total social outcast."),
    ("Parody", "n", ""),
    ("Parsimony", "s", "Purse money-tightly and fiercely guarding your purse money because you are incredibly cheap."),
    ("Partisan", "n", ""),
    ("Patent", "n", ""),
    ("Pathology", "n", ""),
    ("Pathos", "m", '"path" (feeling) = an artistic quality that successfully evokes incredibly deep pity or sadness in the audience.'),
    ("Paucity", "m", '"pauc" (few) = an area suffering from a severe, highly dangerous shortage of resources.'),
    ("Pejorative", "s", "Major dive-an insulting, highly negative word that makes your public reputation take a major dive."),
    ("Pellucid", "m", '"per" (through) + "luc" (light) = water or writing letting maximum light through; perfectly clear and easy to understand.'),
    ("Penchant", "s", "Pendant-wearing a specific, unique pendant every day because you have a massive, natural liking for it."),
    ("Penitent", "s", "Penalty tent-sitting alone in the penalty tent feeling incredibly sorry and guilty for your sins."),
    ("Penultimate", "m", '"paene" (almost) + "ultimus" (last) = the item that is exactly second to last.'),
    ("Penurious", "s", "Penny furious-a guy who becomes furious if he loses even a single penny because he is desperately, severely poor."),
    ("Perfidious", "m", '"per" (through/away) + "fid" (trust) = entirely breaking your faith; highly treacherous and backstabbing.'),
    ("Perfunctory", "m", '"per" (through) + "funct" (perform) = performing a daily task just to get through it, with absolutely zero actual interest or care.'),
    ("Permeate", "m", '"per" (through) + "meare" (pass) = the smell of smoke managing to pass completely through every part of a room.'),
    ("Pernicious", "m", '"per" (completely) + "nec" (death) = spreading a highly dangerous, quiet, and deadly harm.'),
    ("Perplex", "n", ""),
    ("Perspicacity", "m", '"per" (through) + "spec" (look) = looking straight through the noise with incredibly razor-sharp mental insight.'),
    ("Pert", "n", ""),
    ("Pertinacious", "s", "Persistent-fiercely and stubbornly holding onto an opinion with massive persistence."),
    ("Perusal", "n", ""),
    ("Pervasive", "m", '"per" (through) + "vadere" (go) = an idea spreading rapidly and going into absolutely every corner of society.'),
    ("Petulance", "s", "Pet-acting exactly like a moody, highly childish pet throwing a wild tantrum."),
    ("Philanthropic", "m", '"phil" (love) + "anthrop" (human) = giving massive wealth away entirely because of a deep love for humanity.'),
    ("Phlegmatic", "e", 'From the ancient medical theory of the four humors. Doctors believed having too much "phlegm" in your body meant you had a completely sluggish, unexcitable, and deeply calm personality.'),
    ("Pillage", "n", ""),
    ("Pinnacle", "n", ""),
    ("Pithy", "s", "Pity-it's a pity his speech was so incredibly short, but it was highly dense and effective."),
    ("Pittance", "s", "Pity cents-a wage so insultingly tiny they just throw you a few extra cents out of sheer pity."),
    ("Placate", "s", "Play date-setting up a highly fun play date to completely calm down a raging, angry toddler."),
    ("Placid", "s", "Plastic-an ocean surface as completely smooth, calm, and unchanging as solid plastic."),
    ("Platitude", "s", "Flat attitude-offering a flat, highly overused cliché instead of real, helpful advice."),
    ("Plaudits", "m", '"plaudere" (clap) = receiving heavy, wildly enthusiastic applause and praise from the crowd.'),
    ("Plausible", "n", ""),
    ("Plenitude", "m", '"plen" (full) = a completely full, massive abundance of food.'),
]


def main() -> None:
    import json

    lines: list[str] = []
    for word, k, text in HOOK_ROWS:
        if k == "n":
            lines.append(f"{word}\tn")
        else:
            lines.append(f"{word}\t{k}\t{text}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", OUT, "rows", len(HOOK_ROWS))

    # verify against Database slice
    dbp = ROOT.parent / "GlanceSAT" / "GlanceSAT" / "Database.json"
    db = json.loads(dbp.read_text(encoding="utf-8"))
    expect = [r["word"] for r in db[500:750]]
    got = [w for w, _, _ in HOOK_ROWS]
    if got != expect:
        for i, (a, b) in enumerate(zip(got, expect)):
            if a != b:
                print("first mismatch at", i, "got", a, "expected", b)
                break
        raise SystemExit("order mismatch")
    print("order ok vs Database.json[500:750]")


if __name__ == "__main__":
    main()
